### ISSUE TITLE
Direct Link to Case

### ISSUE THREAD

**Issue by larssont** [nbwzx/blddb#8]
Hi,

As a suggestion, it would be nice if you were able to link directly to a specific case. That way you can share the link with others easily, or link to the page from other contexts.

E.g.

https://blddb.net/edge/UF-UR-DB
https://blddb.net/corner/UBL-LDF-DBL

**Comment by nbwzx** [comment]
Thank you for your nice suggestion!
However, it appears that the method you've proposed isn’t a standard way to append parameters to a URL. 
I would prefer the following format: https://blddb.net/edge?position=UF-UR-DB&mode=manmade, as it allows for greater flexibility in including different parameters without confusion.

**Comment by larssont** [comment]
I agree, that's much better, and as you said will allow for more flexibility.

**Comment by nbwzx** [comment]
Appending parameters to URLs has now been implemented in [Version 2](https://v2.blddb.net) ([Introduction](https://github.com/nbwzx/blddb/blob/main/README.md)).
You can try [https://v2.blddb.net/edge?position=UF-UR-DB&mode=manmade](https://v2.blddb.net/edge?position=UF-UR-DB&mode=manmade).
I do not plan to implement this feature in the original site (blddb.net) because the static HTML files make it complex to achieve. Therefore, I will close this issue as completed.
